export const Actions = {
  GET_SHOPPING_LIST_SUCCESS: "GET_SHOPPING_LIST_SUCCESS",
  ADD_LIST_INGREDIENT_SUCCESS: "ADD_LIST_INGREDIENT_SUCCESS",
  UPDATE_LIST_INGREDIENT_SUCCESS: "UPDATE_LIST_INGREDIENT_SUCCESS",
  DELETE_LIST_INGREDIENT_SUCCESS: "DELETE_LIST_INGREDIENT_SUCCESS",

  SET_NEEDS_MAPPING_TRUE: "SET_NEEDS_MAPPING_TRUE",
  SET_NEEDS_MAPPING_FALSE: "SET_NEEDS_MAPPING_FALSE",
  MAP_RECIPES_SUCCESS: "MAP_RECIPES_SUCCESS",

  GET_INGREDIENTS_SUCCESS: "GET_INGREDIENTS_SUCCESS",
  SET_INGREDIENT_TO_EDIT: "SET_INGREDIENT_TO_EDIT",
  RESET_INGREDIENT_TO_EDIT: "RESET_INGREDIENT_TO_EDIT",
  ADD_INGREDIENT_SUCCESS: "ADD_INGREDIENT_SUCCESS",
  UPDATE_INGREDIENT_SUCCESS: "UPDATE_INGREDIENT_SUCCESS",
  DELETE_INGREDIENT_SUCCESS: "DELETE_INGREDIENT_SUCCESS",

  GET_RECIPES_SUCCESS: "GET_RECIPES_SUCCESS",
  ADD_RECIPE_SUCCESS: "ADD_RECIPE_SUCCESS",
  UPDATE_RECIPE_SUCCESS: "UPDATE_RECIPE_SUCCESS",
  DELETE_RECIPE_SUCCESS: "DELETE_RECIPE_SUCCESS",

  SET_INGREDIENT_MODAL_OPEN: "SET_INGREDIENT_MODAL",
  SET_RECIPE_MODAL_OPEN: "SET_RECIPE_MODAL",
  SET_LIST_INGREDIENT_MODAL_OPEN: "SET_LIST_INGREDIENT_MODAL_OPEN",
  SET_MODAL_CLOSED: "SET_MODAL_CLOSED",
  SET_TAB_INDEX: "SET_TAB_INDEX",
  RESET_TAB_INDEX: "RESET_TAB_INDEX",
  SET_ACTIVE_RECIPE: "SET_ACTIVE_RECIPE",
  RESET_ACTIVE_RECIPE: "RESET_ACTIVE_RECIPE",
}