export const cookingUnits = {
  "t": "teaspoon",
  "tsp": "teaspoon",
  "teaspoon": "teaspoon",
  "T": "tablespoon",
  "tbl": "tablespoon",
  "tbs": "tablespoon",
  "tbsp": "tablespoon",
  "tablespoon": "tablespoon",
  "fl oz": "fluid ounce",
  "fluid ounce": "fluid ounce",
  "gill": "gill",
  "c": "cup",
  "cup": "cup",
  "p": "pint",
  "pt": "pint",
  "fl pt": "pint",
  "pint": "pint",
  "q": "quart",
  "qt": "quart",
  "fl qt": "quart",
  "gal": "gallon",
  "gallon": "gallon",
  "ml": "milliliter",
  "millilitre": "milliliter",
  "cc": "milliliter",
  "mL": "milliliter",
  "milliliter": "milliliter",
  "l": "liter",
  "litre": "liter",
  "liter": "liter",
  "L": "liter",
  "dl": "deciliter",
  "decilitre": "deciliter",
  "dL": "deciliter",
  "deciliter": "deciliter",
  "lb": "pound",
  "pound": "pound",
  "oz": "ounce",
  "ounce": "ounce",
  "mg": "milligram",
  "milligramme": "milligram",
  "milligram": "milligram",
  "g": "gram",
  "gramme": "gram",
  "gram": "gram",
  "kg": "kilogram",
  "kilogramme": "kilogram",
  "kilogram": "kilogram"
};